version: '2.4'
services:
  rdbms:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_mysql
    environment:
      MYSQL_DATABASE: orb
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
  redis:
    image: redis:5.0.3
  auth:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_auth
    ports:
      - 80
  user:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_user
    ports:
      - 80
  gateway:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_gateway
    ports:
      - 80