version: '2.4'
services:
  rdbms:
    image: mysql:5.7.25
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  redis:
    image: redis:5.0.3
  auth:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_auth
    ports:
      - 80
  user:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_user
    ports:
      - 80