FROM docker.io/chiaen/base as builder
WORKDIR /go/src/github.com/chiaen/usr
COPY . .
WORKDIR /go/src/github.com/chiaen/usr/auth/server
ENV GO111MODULE=on
RUN go build -o app *.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /go/src/github.com/chiaen/usr/auth/server/app .
CMD ["./app"]