// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{0}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

type ProfileResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Interest             []string `protobuf:"bytes,2,rep,name=interest,proto3" json:"interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{1}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileResponse) GetInterest() []string {
	if m != nil {
		return m.Interest
	}
	return nil
}

type AddInterestRequest struct {
	Interest             string   `protobuf:"bytes,1,opt,name=interest,proto3" json:"interest,omitempty"`
	Published            bool     `protobuf:"varint,2,opt,name=published,proto3" json:"published,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInterestRequest) Reset()         { *m = AddInterestRequest{} }
func (m *AddInterestRequest) String() string { return proto.CompactTextString(m) }
func (*AddInterestRequest) ProtoMessage()    {}
func (*AddInterestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{2}
}

func (m *AddInterestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInterestRequest.Unmarshal(m, b)
}
func (m *AddInterestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInterestRequest.Marshal(b, m, deterministic)
}
func (m *AddInterestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInterestRequest.Merge(m, src)
}
func (m *AddInterestRequest) XXX_Size() int {
	return xxx_messageInfo_AddInterestRequest.Size(m)
}
func (m *AddInterestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInterestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddInterestRequest proto.InternalMessageInfo

func (m *AddInterestRequest) GetInterest() string {
	if m != nil {
		return m.Interest
	}
	return ""
}

func (m *AddInterestRequest) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

type AddInterestResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInterestResponse) Reset()         { *m = AddInterestResponse{} }
func (m *AddInterestResponse) String() string { return proto.CompactTextString(m) }
func (*AddInterestResponse) ProtoMessage()    {}
func (*AddInterestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{3}
}

func (m *AddInterestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInterestResponse.Unmarshal(m, b)
}
func (m *AddInterestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInterestResponse.Marshal(b, m, deterministic)
}
func (m *AddInterestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInterestResponse.Merge(m, src)
}
func (m *AddInterestResponse) XXX_Size() int {
	return xxx_messageInfo_AddInterestResponse.Size(m)
}
func (m *AddInterestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInterestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddInterestResponse proto.InternalMessageInfo

type ListUserByInterestRequest struct {
	Interest             string   `protobuf:"bytes,1,opt,name=interest,proto3" json:"interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserByInterestRequest) Reset()         { *m = ListUserByInterestRequest{} }
func (m *ListUserByInterestRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserByInterestRequest) ProtoMessage()    {}
func (*ListUserByInterestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{4}
}

func (m *ListUserByInterestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserByInterestRequest.Unmarshal(m, b)
}
func (m *ListUserByInterestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserByInterestRequest.Marshal(b, m, deterministic)
}
func (m *ListUserByInterestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserByInterestRequest.Merge(m, src)
}
func (m *ListUserByInterestRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserByInterestRequest.Size(m)
}
func (m *ListUserByInterestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserByInterestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserByInterestRequest proto.InternalMessageInfo

func (m *ListUserByInterestRequest) GetInterest() string {
	if m != nil {
		return m.Interest
	}
	return ""
}

type ListUserByInterestResponse struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserByInterestResponse) Reset()         { *m = ListUserByInterestResponse{} }
func (m *ListUserByInterestResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserByInterestResponse) ProtoMessage()    {}
func (*ListUserByInterestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{5}
}

func (m *ListUserByInterestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserByInterestResponse.Unmarshal(m, b)
}
func (m *ListUserByInterestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserByInterestResponse.Marshal(b, m, deterministic)
}
func (m *ListUserByInterestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserByInterestResponse.Merge(m, src)
}
func (m *ListUserByInterestResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserByInterestResponse.Size(m)
}
func (m *ListUserByInterestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserByInterestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserByInterestResponse proto.InternalMessageInfo

func (m *ListUserByInterestResponse) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProfileRequest)(nil), "usr.api.user.GetProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "usr.api.user.ProfileResponse")
	proto.RegisterType((*AddInterestRequest)(nil), "usr.api.user.AddInterestRequest")
	proto.RegisterType((*AddInterestResponse)(nil), "usr.api.user.AddInterestResponse")
	proto.RegisterType((*ListUserByInterestRequest)(nil), "usr.api.user.ListUserByInterestRequest")
	proto.RegisterType((*ListUserByInterestResponse)(nil), "usr.api.user.ListUserByInterestResponse")
}

func init() { proto.RegisterFile("api/user/user.proto", fileDescriptor_3bc452c1a8bd0aa8) }

var fileDescriptor_3bc452c1a8bd0aa8 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4a, 0xeb, 0x50,
	0x10, 0xc7, 0x49, 0x7a, 0xef, 0xa5, 0x9d, 0x2b, 0x68, 0xa7, 0x2a, 0x31, 0x44, 0x8d, 0x47, 0xc5,
	0xe0, 0x22, 0xc1, 0xba, 0x10, 0x74, 0x65, 0x5d, 0x88, 0x20, 0x22, 0x01, 0x37, 0xee, 0xd2, 0xf6,
	0xb4, 0x3d, 0x90, 0xe6, 0xc4, 0x9c, 0x13, 0x41, 0xc4, 0x8d, 0x7b, 0x57, 0x3e, 0x9a, 0xaf, 0xe0,
	0x03, 0xf8, 0x08, 0x92, 0x8f, 0xa6, 0x8d, 0xf1, 0x03, 0x37, 0x87, 0xcc, 0xf0, 0x9f, 0xff, 0xcc,
	0xfc, 0x32, 0xd0, 0xf2, 0x42, 0xe6, 0xc4, 0x82, 0x46, 0xe9, 0x63, 0x87, 0x11, 0x97, 0x1c, 0xe7,
	0x62, 0x11, 0xd9, 0x5e, 0xc8, 0xec, 0x24, 0xa7, 0x1b, 0x43, 0xce, 0x87, 0x3e, 0x75, 0x12, 0xa5,
	0x17, 0x04, 0x5c, 0x7a, 0x92, 0xf1, 0x40, 0x64, 0x5a, 0xd2, 0x82, 0xe6, 0x29, 0x95, 0x97, 0x11,
	0x1f, 0x30, 0x9f, 0xba, 0xf4, 0x26, 0xa6, 0x42, 0x92, 0x13, 0x98, 0x2f, 0x32, 0x22, 0xe4, 0x81,
	0xa0, 0xb8, 0x08, 0x7f, 0xe9, 0xd8, 0x63, 0xbe, 0xa6, 0x98, 0x8a, 0xd5, 0x70, 0xb3, 0x00, 0x75,
	0xa8, 0xb3, 0x40, 0xd2, 0x88, 0x0a, 0xa9, 0xa9, 0x66, 0xcd, 0x6a, 0xb8, 0x45, 0x4c, 0x2e, 0x00,
	0x8f, 0xfb, 0xfd, 0xb3, 0x3c, 0xcc, 0xad, 0x4b, 0x15, 0x99, 0x55, 0x11, 0xa3, 0x01, 0x8d, 0x30,
	0xee, 0xfa, 0x4c, 0x8c, 0x68, 0x5f, 0x53, 0x4d, 0xc5, 0xaa, 0xbb, 0xd3, 0x04, 0x59, 0x82, 0x56,
	0xc9, 0x2f, 0x1b, 0x8c, 0x1c, 0xc0, 0xca, 0x39, 0x13, 0xf2, 0x4a, 0xd0, 0xa8, 0x73, 0xf7, 0x8b,
	0x6e, 0xa4, 0x0d, 0xfa, 0x67, 0x85, 0xd5, 0x7d, 0x6b, 0xc5, 0xbe, 0xed, 0x37, 0x15, 0xfe, 0x24,
	0x05, 0x38, 0x00, 0x98, 0x62, 0xc3, 0x75, 0x7b, 0x96, 0xb8, 0x5d, 0x01, 0xaa, 0xaf, 0x96, 0x05,
	0x1f, 0xe0, 0x12, 0xed, 0xf1, 0xe5, 0xf5, 0x59, 0x45, 0x5c, 0x70, 0x6e, 0xf7, 0xb2, 0xbf, 0x19,
	0xe6, 0xce, 0x21, 0xfc, 0x9f, 0x59, 0x1a, 0xcd, 0xb2, 0x4f, 0x95, 0xaf, 0xbe, 0xf1, 0x8d, 0x22,
	0xef, 0x66, 0xa4, 0xdd, 0x96, 0x49, 0xb3, 0xe8, 0x36, 0x61, 0x72, 0xa8, 0xec, 0xe2, 0x93, 0x02,
	0x58, 0xe5, 0x82, 0x3b, 0x65, 0xdf, 0x2f, 0x91, 0xeb, 0xd6, 0xcf, 0xc2, 0x7c, 0x8e, 0xad, 0x74,
	0x8e, 0x35, 0x34, 0x2a, 0x73, 0x38, 0xf7, 0x93, 0xaf, 0x87, 0xce, 0xf6, 0xf5, 0xe6, 0x90, 0xc9,
	0x51, 0xdc, 0xb5, 0x7b, 0x7c, 0xec, 0xf4, 0x46, 0xcc, 0xa3, 0x81, 0x13, 0x8b, 0xc8, 0x99, 0x5c,
	0xfe, 0x51, 0xf2, 0x74, 0xff, 0xa5, 0xe7, 0xbc, 0xff, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x36,
	0xde, 0xad, 0x11, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	AddInterest(ctx context.Context, in *AddInterestRequest, opts ...grpc.CallOption) (*AddInterestResponse, error)
	ListUserByInterest(ctx context.Context, in *ListUserByInterestRequest, opts ...grpc.CallOption) (*ListUserByInterestResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/usr.api.user.User/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddInterest(ctx context.Context, in *AddInterestRequest, opts ...grpc.CallOption) (*AddInterestResponse, error) {
	out := new(AddInterestResponse)
	err := c.cc.Invoke(ctx, "/usr.api.user.User/AddInterest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ListUserByInterest(ctx context.Context, in *ListUserByInterestRequest, opts ...grpc.CallOption) (*ListUserByInterestResponse, error) {
	out := new(ListUserByInterestResponse)
	err := c.cc.Invoke(ctx, "/usr.api.user.User/ListUserByInterest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	AddInterest(context.Context, *AddInterestRequest) (*AddInterestResponse, error)
	ListUserByInterest(context.Context, *ListUserByInterestRequest) (*ListUserByInterestResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usr.api.user.User/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usr.api.user.User/AddInterest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddInterest(ctx, req.(*AddInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ListUserByInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserByInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ListUserByInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usr.api.user.User/ListUserByInterest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ListUserByInterest(ctx, req.(*ListUserByInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usr.api.user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _User_GetProfile_Handler,
		},
		{
			MethodName: "AddInterest",
			Handler:    _User_AddInterest_Handler,
		},
		{
			MethodName: "ListUserByInterest",
			Handler:    _User_ListUserByInterest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/user.proto",
}
